//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGuerrero.WSMTCenterServicios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputPagoServicios", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class InputPagoServicios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenterServicios.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referencia1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referencia2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int no_transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        private double montoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenterServicios.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referencia1 {
            get {
                return this.referencia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.referencia1Field, value) != true)) {
                    this.referencia1Field = value;
                    this.RaisePropertyChanged("referencia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referencia2 {
            get {
                return this.referencia2Field;
            }
            set {
                if ((object.ReferenceEquals(this.referencia2Field, value) != true)) {
                    this.referencia2Field = value;
                    this.RaisePropertyChanged("referencia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                if ((this.no_transaccionField.Equals(value) != true)) {
                    this.no_transaccionField = value;
                    this.RaisePropertyChanged("no_transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int cadenaField;
        
        private int establecimientoField;
        
        private int terminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cadena {
            get {
                return this.cadenaField;
            }
            set {
                if ((this.cadenaField.Equals(value) != true)) {
                    this.cadenaField = value;
                    this.RaisePropertyChanged("cadena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                if ((this.establecimientoField.Equals(value) != true)) {
                    this.establecimientoField = value;
                    this.RaisePropertyChanged("establecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int terminal {
            get {
                return this.terminalField;
            }
            set {
                if ((this.terminalField.Equals(value) != true)) {
                    this.terminalField = value;
                    this.RaisePropertyChanged("terminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cajero {
            get {
                return this.cajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.cajeroField, value) != true)) {
                    this.cajeroField = value;
                    this.RaisePropertyChanged("cajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputPagoServicios", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class OutputPagoServicios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenterServicios.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int no_transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_solicitudField;
        
        private int codigo_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcion_respuestaField;
        
        private int no_autorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instruccion1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instruccion2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenterServicios.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                if ((this.no_transaccionField.Equals(value) != true)) {
                    this.no_transaccionField = value;
                    this.RaisePropertyChanged("no_transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_hora_respuesta {
            get {
                return this.fecha_hora_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_respuestaField, value) != true)) {
                    this.fecha_hora_respuestaField = value;
                    this.RaisePropertyChanged("fecha_hora_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fecha_hora_solicitud {
            get {
                return this.fecha_hora_solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_solicitudField, value) != true)) {
                    this.fecha_hora_solicitudField = value;
                    this.RaisePropertyChanged("fecha_hora_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                if ((this.codigo_respuestaField.Equals(value) != true)) {
                    this.codigo_respuestaField = value;
                    this.RaisePropertyChanged("codigo_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcion_respuestaField, value) != true)) {
                    this.descripcion_respuestaField = value;
                    this.RaisePropertyChanged("descripcion_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int no_autorizacion {
            get {
                return this.no_autorizacionField;
            }
            set {
                if ((this.no_autorizacionField.Equals(value) != true)) {
                    this.no_autorizacionField = value;
                    this.RaisePropertyChanged("no_autorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string instruccion1 {
            get {
                return this.instruccion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.instruccion1Field, value) != true)) {
                    this.instruccion1Field = value;
                    this.RaisePropertyChanged("instruccion1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string instruccion2 {
            get {
                return this.instruccion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.instruccion2Field, value) != true)) {
                    this.instruccion2Field = value;
                    this.RaisePropertyChanged("instruccion2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputConsulta", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class InputConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenterServicios.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referencia1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referencia2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int no_transaccion_servicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_servicioField;
        
        private int no_transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenterServicios.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referencia1 {
            get {
                return this.referencia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.referencia1Field, value) != true)) {
                    this.referencia1Field = value;
                    this.RaisePropertyChanged("referencia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referencia2 {
            get {
                return this.referencia2Field;
            }
            set {
                if ((object.ReferenceEquals(this.referencia2Field, value) != true)) {
                    this.referencia2Field = value;
                    this.RaisePropertyChanged("referencia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int no_transaccion_servicio {
            get {
                return this.no_transaccion_servicioField;
            }
            set {
                if ((this.no_transaccion_servicioField.Equals(value) != true)) {
                    this.no_transaccion_servicioField = value;
                    this.RaisePropertyChanged("no_transaccion_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fecha_hora_servicio {
            get {
                return this.fecha_hora_servicioField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_servicioField, value) != true)) {
                    this.fecha_hora_servicioField = value;
                    this.RaisePropertyChanged("fecha_hora_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                if ((this.no_transaccionField.Equals(value) != true)) {
                    this.no_transaccionField = value;
                    this.RaisePropertyChanged("no_transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputConsulta", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class OutputConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenterServicios.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referencia1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referencia2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int no_transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_solicitudField;
        
        private int codigo_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcion_respuestaField;
        
        private int no_autorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instruccion1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instruccion2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenterServicios.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referencia1 {
            get {
                return this.referencia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.referencia1Field, value) != true)) {
                    this.referencia1Field = value;
                    this.RaisePropertyChanged("referencia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referencia2 {
            get {
                return this.referencia2Field;
            }
            set {
                if ((object.ReferenceEquals(this.referencia2Field, value) != true)) {
                    this.referencia2Field = value;
                    this.RaisePropertyChanged("referencia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                if ((this.no_transaccionField.Equals(value) != true)) {
                    this.no_transaccionField = value;
                    this.RaisePropertyChanged("no_transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fecha_hora_respuesta {
            get {
                return this.fecha_hora_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_respuestaField, value) != true)) {
                    this.fecha_hora_respuestaField = value;
                    this.RaisePropertyChanged("fecha_hora_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fecha_hora_solicitud {
            get {
                return this.fecha_hora_solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_solicitudField, value) != true)) {
                    this.fecha_hora_solicitudField = value;
                    this.RaisePropertyChanged("fecha_hora_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                if ((this.codigo_respuestaField.Equals(value) != true)) {
                    this.codigo_respuestaField = value;
                    this.RaisePropertyChanged("codigo_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcion_respuestaField, value) != true)) {
                    this.descripcion_respuestaField = value;
                    this.RaisePropertyChanged("descripcion_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int no_autorizacion {
            get {
                return this.no_autorizacionField;
            }
            set {
                if ((this.no_autorizacionField.Equals(value) != true)) {
                    this.no_autorizacionField = value;
                    this.RaisePropertyChanged("no_autorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string instruccion1 {
            get {
                return this.instruccion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.instruccion1Field, value) != true)) {
                    this.instruccion1Field = value;
                    this.RaisePropertyChanged("instruccion1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string instruccion2 {
            get {
                return this.instruccion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.instruccion2Field, value) != true)) {
                    this.instruccion2Field = value;
                    this.RaisePropertyChanged("instruccion2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputSaldo", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class InputSaldo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenterServicios.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenterServicios.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputSaldo", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class OutputSaldo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenterServicios.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        private int codigo_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcion_respuestaField;
        
        private decimal saldoField;
        
        private decimal creditoField;
        
        private bool aplicaCreditoField;
        
        private decimal limiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenterServicios.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                if ((this.codigo_respuestaField.Equals(value) != true)) {
                    this.codigo_respuestaField = value;
                    this.RaisePropertyChanged("codigo_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcion_respuestaField, value) != true)) {
                    this.descripcion_respuestaField = value;
                    this.RaisePropertyChanged("descripcion_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal credito {
            get {
                return this.creditoField;
            }
            set {
                if ((this.creditoField.Equals(value) != true)) {
                    this.creditoField = value;
                    this.RaisePropertyChanged("credito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool aplicaCredito {
            get {
                return this.aplicaCreditoField;
            }
            set {
                if ((this.aplicaCreditoField.Equals(value) != true)) {
                    this.aplicaCreditoField = value;
                    this.RaisePropertyChanged("aplicaCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal limite {
            get {
                return this.limiteField;
            }
            set {
                if ((this.limiteField.Equals(value) != true)) {
                    this.limiteField = value;
                    this.RaisePropertyChanged("limite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", ConfigurationName="WSMTCenterServicios.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento inputServicio del espacio de nombres http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/servicio", ReplyAction="*")]
        CasaGuerrero.WSMTCenterServicios.servicioResponse servicio(CasaGuerrero.WSMTCenterServicios.servicioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/servicio", ReplyAction="*")]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.servicioResponse> servicioAsync(CasaGuerrero.WSMTCenterServicios.servicioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento inputConsulta del espacio de nombres http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/consulta", ReplyAction="*")]
        CasaGuerrero.WSMTCenterServicios.consultaResponse consulta(CasaGuerrero.WSMTCenterServicios.consultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.consultaResponse> consultaAsync(CasaGuerrero.WSMTCenterServicios.consultaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento inputSaldo del espacio de nombres http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/saldo", ReplyAction="*")]
        CasaGuerrero.WSMTCenterServicios.saldoResponse saldo(CasaGuerrero.WSMTCenterServicios.saldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/saldo", ReplyAction="*")]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.saldoResponse> saldoAsync(CasaGuerrero.WSMTCenterServicios.saldoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class servicioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="servicio", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenterServicios.servicioRequestBody Body;
        
        public servicioRequest() {
        }
        
        public servicioRequest(CasaGuerrero.WSMTCenterServicios.servicioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class servicioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenterServicios.InputPagoServicios inputServicio;
        
        public servicioRequestBody() {
        }
        
        public servicioRequestBody(CasaGuerrero.WSMTCenterServicios.InputPagoServicios inputServicio) {
            this.inputServicio = inputServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class servicioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="servicioResponse", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenterServicios.servicioResponseBody Body;
        
        public servicioResponse() {
        }
        
        public servicioResponse(CasaGuerrero.WSMTCenterServicios.servicioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class servicioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenterServicios.OutputPagoServicios servicioResult;
        
        public servicioResponseBody() {
        }
        
        public servicioResponseBody(CasaGuerrero.WSMTCenterServicios.OutputPagoServicios servicioResult) {
            this.servicioResult = servicioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenterServicios.consultaRequestBody Body;
        
        public consultaRequest() {
        }
        
        public consultaRequest(CasaGuerrero.WSMTCenterServicios.consultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class consultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenterServicios.InputConsulta inputConsulta;
        
        public consultaRequestBody() {
        }
        
        public consultaRequestBody(CasaGuerrero.WSMTCenterServicios.InputConsulta inputConsulta) {
            this.inputConsulta = inputConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaResponse", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenterServicios.consultaResponseBody Body;
        
        public consultaResponse() {
        }
        
        public consultaResponse(CasaGuerrero.WSMTCenterServicios.consultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class consultaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenterServicios.OutputConsulta consultaResult;
        
        public consultaResponseBody() {
        }
        
        public consultaResponseBody(CasaGuerrero.WSMTCenterServicios.OutputConsulta consultaResult) {
            this.consultaResult = consultaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saldo", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenterServicios.saldoRequestBody Body;
        
        public saldoRequest() {
        }
        
        public saldoRequest(CasaGuerrero.WSMTCenterServicios.saldoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class saldoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenterServicios.InputSaldo inputSaldo;
        
        public saldoRequestBody() {
        }
        
        public saldoRequestBody(CasaGuerrero.WSMTCenterServicios.InputSaldo inputSaldo) {
            this.inputSaldo = inputSaldo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saldoResponse", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenterServicios.saldoResponseBody Body;
        
        public saldoResponse() {
        }
        
        public saldoResponse(CasaGuerrero.WSMTCenterServicios.saldoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class saldoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenterServicios.OutputSaldo saldoResult;
        
        public saldoResponseBody() {
        }
        
        public saldoResponseBody(CasaGuerrero.WSMTCenterServicios.OutputSaldo saldoResult) {
            this.saldoResult = saldoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : CasaGuerrero.WSMTCenterServicios.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<CasaGuerrero.WSMTCenterServicios.ServiceSoap>, CasaGuerrero.WSMTCenterServicios.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CasaGuerrero.WSMTCenterServicios.servicioResponse CasaGuerrero.WSMTCenterServicios.ServiceSoap.servicio(CasaGuerrero.WSMTCenterServicios.servicioRequest request) {
            return base.Channel.servicio(request);
        }
        
        public CasaGuerrero.WSMTCenterServicios.OutputPagoServicios servicio(CasaGuerrero.WSMTCenterServicios.InputPagoServicios inputServicio) {
            CasaGuerrero.WSMTCenterServicios.servicioRequest inValue = new CasaGuerrero.WSMTCenterServicios.servicioRequest();
            inValue.Body = new CasaGuerrero.WSMTCenterServicios.servicioRequestBody();
            inValue.Body.inputServicio = inputServicio;
            CasaGuerrero.WSMTCenterServicios.servicioResponse retVal = ((CasaGuerrero.WSMTCenterServicios.ServiceSoap)(this)).servicio(inValue);
            return retVal.Body.servicioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.servicioResponse> CasaGuerrero.WSMTCenterServicios.ServiceSoap.servicioAsync(CasaGuerrero.WSMTCenterServicios.servicioRequest request) {
            return base.Channel.servicioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.servicioResponse> servicioAsync(CasaGuerrero.WSMTCenterServicios.InputPagoServicios inputServicio) {
            CasaGuerrero.WSMTCenterServicios.servicioRequest inValue = new CasaGuerrero.WSMTCenterServicios.servicioRequest();
            inValue.Body = new CasaGuerrero.WSMTCenterServicios.servicioRequestBody();
            inValue.Body.inputServicio = inputServicio;
            return ((CasaGuerrero.WSMTCenterServicios.ServiceSoap)(this)).servicioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CasaGuerrero.WSMTCenterServicios.consultaResponse CasaGuerrero.WSMTCenterServicios.ServiceSoap.consulta(CasaGuerrero.WSMTCenterServicios.consultaRequest request) {
            return base.Channel.consulta(request);
        }
        
        public CasaGuerrero.WSMTCenterServicios.OutputConsulta consulta(CasaGuerrero.WSMTCenterServicios.InputConsulta inputConsulta) {
            CasaGuerrero.WSMTCenterServicios.consultaRequest inValue = new CasaGuerrero.WSMTCenterServicios.consultaRequest();
            inValue.Body = new CasaGuerrero.WSMTCenterServicios.consultaRequestBody();
            inValue.Body.inputConsulta = inputConsulta;
            CasaGuerrero.WSMTCenterServicios.consultaResponse retVal = ((CasaGuerrero.WSMTCenterServicios.ServiceSoap)(this)).consulta(inValue);
            return retVal.Body.consultaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.consultaResponse> CasaGuerrero.WSMTCenterServicios.ServiceSoap.consultaAsync(CasaGuerrero.WSMTCenterServicios.consultaRequest request) {
            return base.Channel.consultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.consultaResponse> consultaAsync(CasaGuerrero.WSMTCenterServicios.InputConsulta inputConsulta) {
            CasaGuerrero.WSMTCenterServicios.consultaRequest inValue = new CasaGuerrero.WSMTCenterServicios.consultaRequest();
            inValue.Body = new CasaGuerrero.WSMTCenterServicios.consultaRequestBody();
            inValue.Body.inputConsulta = inputConsulta;
            return ((CasaGuerrero.WSMTCenterServicios.ServiceSoap)(this)).consultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CasaGuerrero.WSMTCenterServicios.saldoResponse CasaGuerrero.WSMTCenterServicios.ServiceSoap.saldo(CasaGuerrero.WSMTCenterServicios.saldoRequest request) {
            return base.Channel.saldo(request);
        }
        
        public CasaGuerrero.WSMTCenterServicios.OutputSaldo saldo(CasaGuerrero.WSMTCenterServicios.InputSaldo inputSaldo) {
            CasaGuerrero.WSMTCenterServicios.saldoRequest inValue = new CasaGuerrero.WSMTCenterServicios.saldoRequest();
            inValue.Body = new CasaGuerrero.WSMTCenterServicios.saldoRequestBody();
            inValue.Body.inputSaldo = inputSaldo;
            CasaGuerrero.WSMTCenterServicios.saldoResponse retVal = ((CasaGuerrero.WSMTCenterServicios.ServiceSoap)(this)).saldo(inValue);
            return retVal.Body.saldoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.saldoResponse> CasaGuerrero.WSMTCenterServicios.ServiceSoap.saldoAsync(CasaGuerrero.WSMTCenterServicios.saldoRequest request) {
            return base.Channel.saldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CasaGuerrero.WSMTCenterServicios.saldoResponse> saldoAsync(CasaGuerrero.WSMTCenterServicios.InputSaldo inputSaldo) {
            CasaGuerrero.WSMTCenterServicios.saldoRequest inValue = new CasaGuerrero.WSMTCenterServicios.saldoRequest();
            inValue.Body = new CasaGuerrero.WSMTCenterServicios.saldoRequestBody();
            inValue.Body.inputSaldo = inputSaldo;
            return ((CasaGuerrero.WSMTCenterServicios.ServiceSoap)(this)).saldoAsync(inValue);
        }
    }
}
