//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CasaGuerrero.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback recargaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback saldoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::CasaGuerrero.Properties.Settings.Default.CasaGuerrero_WebReference_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event recargaCompletedEventHandler recargaCompleted;
        
        /// <remarks/>
        public event consultaCompletedEventHandler consultaCompleted;
        
        /// <remarks/>
        public event saldoCompletedEventHandler saldoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/recarga", RequestNamespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", ResponseNamespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OutputRecarga recarga(InputRecarga inputRecarga) {
            object[] results = this.Invoke("recarga", new object[] {
                        inputRecarga});
            return ((OutputRecarga)(results[0]));
        }
        
        /// <remarks/>
        public void recargaAsync(InputRecarga inputRecarga) {
            this.recargaAsync(inputRecarga, null);
        }
        
        /// <remarks/>
        public void recargaAsync(InputRecarga inputRecarga, object userState) {
            if ((this.recargaOperationCompleted == null)) {
                this.recargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecargaOperationCompleted);
            }
            this.InvokeAsync("recarga", new object[] {
                        inputRecarga}, this.recargaOperationCompleted, userState);
        }
        
        private void OnrecargaOperationCompleted(object arg) {
            if ((this.recargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recargaCompleted(this, new recargaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/consulta", RequestNamespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", ResponseNamespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OutputConsulta consulta(InputConsulta inputConsulta) {
            object[] results = this.Invoke("consulta", new object[] {
                        inputConsulta});
            return ((OutputConsulta)(results[0]));
        }
        
        /// <remarks/>
        public void consultaAsync(InputConsulta inputConsulta) {
            this.consultaAsync(inputConsulta, null);
        }
        
        /// <remarks/>
        public void consultaAsync(InputConsulta inputConsulta, object userState) {
            if ((this.consultaOperationCompleted == null)) {
                this.consultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaOperationCompleted);
            }
            this.InvokeAsync("consulta", new object[] {
                        inputConsulta}, this.consultaOperationCompleted, userState);
        }
        
        private void OnconsultaOperationCompleted(object arg) {
            if ((this.consultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCompleted(this, new consultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/saldo", RequestNamespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", ResponseNamespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OutputSaldo saldo(InputSaldo inputSaldo) {
            object[] results = this.Invoke("saldo", new object[] {
                        inputSaldo});
            return ((OutputSaldo)(results[0]));
        }
        
        /// <remarks/>
        public void saldoAsync(InputSaldo inputSaldo) {
            this.saldoAsync(inputSaldo, null);
        }
        
        /// <remarks/>
        public void saldoAsync(InputSaldo inputSaldo, object userState) {
            if ((this.saldoOperationCompleted == null)) {
                this.saldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaldoOperationCompleted);
            }
            this.InvokeAsync("saldo", new object[] {
                        inputSaldo}, this.saldoOperationCompleted, userState);
        }
        
        private void OnsaldoOperationCompleted(object arg) {
            if ((this.saldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saldoCompleted(this, new saldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class InputRecarga {
        
        private Cuenta cuentaField;
        
        private string telefonoField;
        
        private string skuField;
        
        private int no_transaccionField;
        
        private string fecha_horaField;
        
        private string cve_estadoField;
        
        /// <comentarios/>
        public Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
        
        /// <comentarios/>
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                this.no_transaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                this.fecha_horaField = value;
            }
        }
        
        /// <comentarios/>
        public string cve_estado {
            get {
                return this.cve_estadoField;
            }
            set {
                this.cve_estadoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class Cuenta {
        
        private int cadenaField;
        
        private int establecimientoField;
        
        private int terminalField;
        
        private string cajeroField;
        
        private string claveField;
        
        /// <comentarios/>
        public int cadena {
            get {
                return this.cadenaField;
            }
            set {
                this.cadenaField = value;
            }
        }
        
        /// <comentarios/>
        public int establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
            }
        }
        
        /// <comentarios/>
        public int terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <comentarios/>
        public string cajero {
            get {
                return this.cajeroField;
            }
            set {
                this.cajeroField = value;
            }
        }
        
        /// <comentarios/>
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class OutputSaldo {
        
        private Cuenta cuentaField;
        
        private string fecha_horaField;
        
        private int codigo_respuestaField;
        
        private string descripcion_respuestaField;
        
        private decimal saldoField;
        
        private decimal creditoField;
        
        private bool aplicaCreditoField;
        
        private decimal limiteField;
        
        /// <comentarios/>
        public Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                this.fecha_horaField = value;
            }
        }
        
        /// <comentarios/>
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                this.codigo_respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                this.descripcion_respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public decimal saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <comentarios/>
        public decimal credito {
            get {
                return this.creditoField;
            }
            set {
                this.creditoField = value;
            }
        }
        
        /// <comentarios/>
        public bool aplicaCredito {
            get {
                return this.aplicaCreditoField;
            }
            set {
                this.aplicaCreditoField = value;
            }
        }
        
        /// <comentarios/>
        public decimal limite {
            get {
                return this.limiteField;
            }
            set {
                this.limiteField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class InputSaldo {
        
        private Cuenta cuentaField;
        
        private string fecha_horaField;
        
        /// <comentarios/>
        public Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                this.fecha_horaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class OutputConsulta {
        
        private Cuenta cuentaField;
        
        private string telefonoField;
        
        private string skuField;
        
        private int no_transaccionField;
        
        private string fecha_horaField;
        
        private string fecha_hora_respuestaField;
        
        private string fecha_hora_solicitudField;
        
        private int codigo_respuestaField;
        
        private string descripcion_respuestaField;
        
        private int no_autorizacionField;
        
        private string instruccion1Field;
        
        private string instruccion2Field;
        
        /// <comentarios/>
        public Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
        
        /// <comentarios/>
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                this.no_transaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                this.fecha_horaField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora_respuesta {
            get {
                return this.fecha_hora_respuestaField;
            }
            set {
                this.fecha_hora_respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora_solicitud {
            get {
                return this.fecha_hora_solicitudField;
            }
            set {
                this.fecha_hora_solicitudField = value;
            }
        }
        
        /// <comentarios/>
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                this.codigo_respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                this.descripcion_respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public int no_autorizacion {
            get {
                return this.no_autorizacionField;
            }
            set {
                this.no_autorizacionField = value;
            }
        }
        
        /// <comentarios/>
        public string instruccion1 {
            get {
                return this.instruccion1Field;
            }
            set {
                this.instruccion1Field = value;
            }
        }
        
        /// <comentarios/>
        public string instruccion2 {
            get {
                return this.instruccion2Field;
            }
            set {
                this.instruccion2Field = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class InputConsulta {
        
        private Cuenta cuentaField;
        
        private string telefonoField;
        
        private string skuField;
        
        private int no_transaccion_recargaField;
        
        private string fecha_hora_recargaField;
        
        private int no_transaccionField;
        
        private string fecha_horaField;
        
        /// <comentarios/>
        public Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
        
        /// <comentarios/>
        public int no_transaccion_recarga {
            get {
                return this.no_transaccion_recargaField;
            }
            set {
                this.no_transaccion_recargaField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora_recarga {
            get {
                return this.fecha_hora_recargaField;
            }
            set {
                this.fecha_hora_recargaField = value;
            }
        }
        
        /// <comentarios/>
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                this.no_transaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                this.fecha_horaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class OutputRecarga {
        
        private Cuenta cuentaField;
        
        private string telefonoField;
        
        private string skuField;
        
        private int no_transaccionField;
        
        private string fecha_horaField;
        
        private string fecha_hora_respuestaField;
        
        private string fecha_hora_solicitudField;
        
        private string cve_estadoField;
        
        private int codigo_respuestaField;
        
        private string descripcion_respuestaField;
        
        private int no_autorizacionField;
        
        private string instruccion1Field;
        
        private string instruccion2Field;
        
        /// <comentarios/>
        public Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
        
        /// <comentarios/>
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                this.no_transaccionField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                this.fecha_horaField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora_respuesta {
            get {
                return this.fecha_hora_respuestaField;
            }
            set {
                this.fecha_hora_respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string fecha_hora_solicitud {
            get {
                return this.fecha_hora_solicitudField;
            }
            set {
                this.fecha_hora_solicitudField = value;
            }
        }
        
        /// <comentarios/>
        public string cve_estado {
            get {
                return this.cve_estadoField;
            }
            set {
                this.cve_estadoField = value;
            }
        }
        
        /// <comentarios/>
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                this.codigo_respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                this.descripcion_respuestaField = value;
            }
        }
        
        /// <comentarios/>
        public int no_autorizacion {
            get {
                return this.no_autorizacionField;
            }
            set {
                this.no_autorizacionField = value;
            }
        }
        
        /// <comentarios/>
        public string instruccion1 {
            get {
                return this.instruccion1Field;
            }
            set {
                this.instruccion1Field = value;
            }
        }
        
        /// <comentarios/>
        public string instruccion2 {
            get {
                return this.instruccion2Field;
            }
            set {
                this.instruccion2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void recargaCompletedEventHandler(object sender, recargaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recargaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recargaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputRecarga Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputRecarga)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void consultaCompletedEventHandler(object sender, consultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputConsulta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputConsulta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void saldoCompletedEventHandler(object sender, saldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputSaldo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputSaldo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591