//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGuerrero.WSMTCenter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputRecarga", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class InputRecarga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenter.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int no_transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cve_estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenter.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                if ((this.no_transaccionField.Equals(value) != true)) {
                    this.no_transaccionField = value;
                    this.RaisePropertyChanged("no_transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cve_estado {
            get {
                return this.cve_estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.cve_estadoField, value) != true)) {
                    this.cve_estadoField = value;
                    this.RaisePropertyChanged("cve_estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int cadenaField;
        
        private int establecimientoField;
        
        private int terminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cadena {
            get {
                return this.cadenaField;
            }
            set {
                if ((this.cadenaField.Equals(value) != true)) {
                    this.cadenaField = value;
                    this.RaisePropertyChanged("cadena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                if ((this.establecimientoField.Equals(value) != true)) {
                    this.establecimientoField = value;
                    this.RaisePropertyChanged("establecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int terminal {
            get {
                return this.terminalField;
            }
            set {
                if ((this.terminalField.Equals(value) != true)) {
                    this.terminalField = value;
                    this.RaisePropertyChanged("terminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cajero {
            get {
                return this.cajeroField;
            }
            set {
                if ((object.ReferenceEquals(this.cajeroField, value) != true)) {
                    this.cajeroField = value;
                    this.RaisePropertyChanged("cajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        public static implicit operator Cuenta(string v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputRecarga", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class OutputRecarga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenter.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int no_transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cve_estadoField;
        
        private int codigo_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcion_respuestaField;
        
        private int no_autorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instruccion1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instruccion2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenter.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                if ((this.no_transaccionField.Equals(value) != true)) {
                    this.no_transaccionField = value;
                    this.RaisePropertyChanged("no_transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fecha_hora_respuesta {
            get {
                return this.fecha_hora_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_respuestaField, value) != true)) {
                    this.fecha_hora_respuestaField = value;
                    this.RaisePropertyChanged("fecha_hora_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fecha_hora_solicitud {
            get {
                return this.fecha_hora_solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_solicitudField, value) != true)) {
                    this.fecha_hora_solicitudField = value;
                    this.RaisePropertyChanged("fecha_hora_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cve_estado {
            get {
                return this.cve_estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.cve_estadoField, value) != true)) {
                    this.cve_estadoField = value;
                    this.RaisePropertyChanged("cve_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                if ((this.codigo_respuestaField.Equals(value) != true)) {
                    this.codigo_respuestaField = value;
                    this.RaisePropertyChanged("codigo_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcion_respuestaField, value) != true)) {
                    this.descripcion_respuestaField = value;
                    this.RaisePropertyChanged("descripcion_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int no_autorizacion {
            get {
                return this.no_autorizacionField;
            }
            set {
                if ((this.no_autorizacionField.Equals(value) != true)) {
                    this.no_autorizacionField = value;
                    this.RaisePropertyChanged("no_autorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string instruccion1 {
            get {
                return this.instruccion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.instruccion1Field, value) != true)) {
                    this.instruccion1Field = value;
                    this.RaisePropertyChanged("instruccion1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string instruccion2 {
            get {
                return this.instruccion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.instruccion2Field, value) != true)) {
                    this.instruccion2Field = value;
                    this.RaisePropertyChanged("instruccion2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputConsulta", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class InputConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenter.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int no_transaccion_recargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_recargaField;
        
        private int no_transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenter.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int no_transaccion_recarga {
            get {
                return this.no_transaccion_recargaField;
            }
            set {
                if ((this.no_transaccion_recargaField.Equals(value) != true)) {
                    this.no_transaccion_recargaField = value;
                    this.RaisePropertyChanged("no_transaccion_recarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_hora_recarga {
            get {
                return this.fecha_hora_recargaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_recargaField, value) != true)) {
                    this.fecha_hora_recargaField = value;
                    this.RaisePropertyChanged("fecha_hora_recarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                if ((this.no_transaccionField.Equals(value) != true)) {
                    this.no_transaccionField = value;
                    this.RaisePropertyChanged("no_transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputConsulta", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class OutputConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenter.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        private int no_transaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_hora_solicitudField;
        
        private int codigo_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcion_respuestaField;
        
        private int no_autorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instruccion1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instruccion2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenter.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int no_transaccion {
            get {
                return this.no_transaccionField;
            }
            set {
                if ((this.no_transaccionField.Equals(value) != true)) {
                    this.no_transaccionField = value;
                    this.RaisePropertyChanged("no_transaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fecha_hora_respuesta {
            get {
                return this.fecha_hora_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_respuestaField, value) != true)) {
                    this.fecha_hora_respuestaField = value;
                    this.RaisePropertyChanged("fecha_hora_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fecha_hora_solicitud {
            get {
                return this.fecha_hora_solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_hora_solicitudField, value) != true)) {
                    this.fecha_hora_solicitudField = value;
                    this.RaisePropertyChanged("fecha_hora_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                if ((this.codigo_respuestaField.Equals(value) != true)) {
                    this.codigo_respuestaField = value;
                    this.RaisePropertyChanged("codigo_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcion_respuestaField, value) != true)) {
                    this.descripcion_respuestaField = value;
                    this.RaisePropertyChanged("descripcion_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int no_autorizacion {
            get {
                return this.no_autorizacionField;
            }
            set {
                if ((this.no_autorizacionField.Equals(value) != true)) {
                    this.no_autorizacionField = value;
                    this.RaisePropertyChanged("no_autorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string instruccion1 {
            get {
                return this.instruccion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.instruccion1Field, value) != true)) {
                    this.instruccion1Field = value;
                    this.RaisePropertyChanged("instruccion1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string instruccion2 {
            get {
                return this.instruccion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.instruccion2Field, value) != true)) {
                    this.instruccion2Field = value;
                    this.RaisePropertyChanged("instruccion2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputSaldo", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class InputSaldo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenter.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenter.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputSaldo", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    [System.SerializableAttribute()]
    public partial class OutputSaldo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CasaGuerrero.WSMTCenter.Cuenta cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_horaField;
        
        private int codigo_respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcion_respuestaField;
        
        private decimal saldoField;
        
        private decimal creditoField;
        
        private bool aplicaCreditoField;
        
        private decimal limiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CasaGuerrero.WSMTCenter.Cuenta cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_horaField, value) != true)) {
                    this.fecha_horaField = value;
                    this.RaisePropertyChanged("fecha_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int codigo_respuesta {
            get {
                return this.codigo_respuestaField;
            }
            set {
                if ((this.codigo_respuestaField.Equals(value) != true)) {
                    this.codigo_respuestaField = value;
                    this.RaisePropertyChanged("codigo_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion_respuesta {
            get {
                return this.descripcion_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcion_respuestaField, value) != true)) {
                    this.descripcion_respuestaField = value;
                    this.RaisePropertyChanged("descripcion_respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal credito {
            get {
                return this.creditoField;
            }
            set {
                if ((this.creditoField.Equals(value) != true)) {
                    this.creditoField = value;
                    this.RaisePropertyChanged("credito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool aplicaCredito {
            get {
                return this.aplicaCreditoField;
            }
            set {
                if ((this.aplicaCreditoField.Equals(value) != true)) {
                    this.aplicaCreditoField = value;
                    this.RaisePropertyChanged("aplicaCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal limite {
            get {
                return this.limiteField;
            }
            set {
                if ((this.limiteField.Equals(value) != true)) {
                    this.limiteField = value;
                    this.RaisePropertyChanged("limite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", ConfigurationName="WSMTCenter.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento inputRecarga del espacio de nombres http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/recarga", ReplyAction="*")]
        CasaGuerrero.WSMTCenter.recargaResponse recarga(CasaGuerrero.WSMTCenter.recargaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/recarga", ReplyAction="*")]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.recargaResponse> recargaAsync(CasaGuerrero.WSMTCenter.recargaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento inputConsulta del espacio de nombres http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/consulta", ReplyAction="*")]
        CasaGuerrero.WSMTCenter.consultaResponse consulta(CasaGuerrero.WSMTCenter.consultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.consultaResponse> consultaAsync(CasaGuerrero.WSMTCenter.consultaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento inputSaldo del espacio de nombres http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/saldo", ReplyAction="*")]
        CasaGuerrero.WSMTCenter.saldoResponse saldo(CasaGuerrero.WSMTCenter.saldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional/saldo", ReplyAction="*")]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.saldoResponse> saldoAsync(CasaGuerrero.WSMTCenter.saldoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recargaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recarga", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenter.recargaRequestBody Body;
        
        public recargaRequest() {
        }
        
        public recargaRequest(CasaGuerrero.WSMTCenter.recargaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class recargaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenter.InputRecarga inputRecarga;
        
        public recargaRequestBody() {
        }
        
        public recargaRequestBody(CasaGuerrero.WSMTCenter.InputRecarga inputRecarga) {
            this.inputRecarga = inputRecarga;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recargaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recargaResponse", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenter.recargaResponseBody Body;
        
        public recargaResponse() {
        }
        
        public recargaResponse(CasaGuerrero.WSMTCenter.recargaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class recargaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenter.OutputRecarga recargaResult;
        
        public recargaResponseBody() {
        }
        
        public recargaResponseBody(CasaGuerrero.WSMTCenter.OutputRecarga recargaResult) {
            this.recargaResult = recargaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenter.consultaRequestBody Body;
        
        public consultaRequest() {
        }
        
        public consultaRequest(CasaGuerrero.WSMTCenter.consultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class consultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenter.InputConsulta inputConsulta;
        
        public consultaRequestBody() {
        }
        
        public consultaRequestBody(CasaGuerrero.WSMTCenter.InputConsulta inputConsulta) {
            this.inputConsulta = inputConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaResponse", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenter.consultaResponseBody Body;
        
        public consultaResponse() {
        }
        
        public consultaResponse(CasaGuerrero.WSMTCenter.consultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class consultaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenter.OutputConsulta consultaResult;
        
        public consultaResponseBody() {
        }
        
        public consultaResponseBody(CasaGuerrero.WSMTCenter.OutputConsulta consultaResult) {
            this.consultaResult = consultaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saldo", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenter.saldoRequestBody Body;
        
        public saldoRequest() {
        }
        
        public saldoRequest(CasaGuerrero.WSMTCenter.saldoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class saldoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenter.InputSaldo inputSaldo;
        
        public saldoRequestBody() {
        }
        
        public saldoRequestBody(CasaGuerrero.WSMTCenter.InputSaldo inputSaldo) {
            this.inputSaldo = inputSaldo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saldoResponse", Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional", Order=0)]
        public CasaGuerrero.WSMTCenter.saldoResponseBody Body;
        
        public saldoResponse() {
        }
        
        public saldoResponse(CasaGuerrero.WSMTCenter.saldoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/WebServOrdersTransactional/ServOrdersTransactional")]
    public partial class saldoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CasaGuerrero.WSMTCenter.OutputSaldo saldoResult;
        
        public saldoResponseBody() {
        }
        
        public saldoResponseBody(CasaGuerrero.WSMTCenter.OutputSaldo saldoResult) {
            this.saldoResult = saldoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : CasaGuerrero.WSMTCenter.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<CasaGuerrero.WSMTCenter.ServiceSoap>, CasaGuerrero.WSMTCenter.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CasaGuerrero.WSMTCenter.recargaResponse CasaGuerrero.WSMTCenter.ServiceSoap.recarga(CasaGuerrero.WSMTCenter.recargaRequest request) {
            return base.Channel.recarga(request);
        }
        
        public CasaGuerrero.WSMTCenter.OutputRecarga recarga(CasaGuerrero.WSMTCenter.InputRecarga inputRecarga) {
            CasaGuerrero.WSMTCenter.recargaRequest inValue = new CasaGuerrero.WSMTCenter.recargaRequest();
            inValue.Body = new CasaGuerrero.WSMTCenter.recargaRequestBody();
            inValue.Body.inputRecarga = inputRecarga;
            CasaGuerrero.WSMTCenter.recargaResponse retVal = ((CasaGuerrero.WSMTCenter.ServiceSoap)(this)).recarga(inValue);
            return retVal.Body.recargaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.recargaResponse> CasaGuerrero.WSMTCenter.ServiceSoap.recargaAsync(CasaGuerrero.WSMTCenter.recargaRequest request) {
            return base.Channel.recargaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.recargaResponse> recargaAsync(CasaGuerrero.WSMTCenter.InputRecarga inputRecarga) {
            CasaGuerrero.WSMTCenter.recargaRequest inValue = new CasaGuerrero.WSMTCenter.recargaRequest();
            inValue.Body = new CasaGuerrero.WSMTCenter.recargaRequestBody();
            inValue.Body.inputRecarga = inputRecarga;
            return ((CasaGuerrero.WSMTCenter.ServiceSoap)(this)).recargaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CasaGuerrero.WSMTCenter.consultaResponse CasaGuerrero.WSMTCenter.ServiceSoap.consulta(CasaGuerrero.WSMTCenter.consultaRequest request) {
            return base.Channel.consulta(request);
        }
        
        public CasaGuerrero.WSMTCenter.OutputConsulta consulta(CasaGuerrero.WSMTCenter.InputConsulta inputConsulta) {
            CasaGuerrero.WSMTCenter.consultaRequest inValue = new CasaGuerrero.WSMTCenter.consultaRequest();
            inValue.Body = new CasaGuerrero.WSMTCenter.consultaRequestBody();
            inValue.Body.inputConsulta = inputConsulta;
            CasaGuerrero.WSMTCenter.consultaResponse retVal = ((CasaGuerrero.WSMTCenter.ServiceSoap)(this)).consulta(inValue);
            return retVal.Body.consultaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.consultaResponse> CasaGuerrero.WSMTCenter.ServiceSoap.consultaAsync(CasaGuerrero.WSMTCenter.consultaRequest request) {
            return base.Channel.consultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.consultaResponse> consultaAsync(CasaGuerrero.WSMTCenter.InputConsulta inputConsulta) {
            CasaGuerrero.WSMTCenter.consultaRequest inValue = new CasaGuerrero.WSMTCenter.consultaRequest();
            inValue.Body = new CasaGuerrero.WSMTCenter.consultaRequestBody();
            inValue.Body.inputConsulta = inputConsulta;
            return ((CasaGuerrero.WSMTCenter.ServiceSoap)(this)).consultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CasaGuerrero.WSMTCenter.saldoResponse CasaGuerrero.WSMTCenter.ServiceSoap.saldo(CasaGuerrero.WSMTCenter.saldoRequest request) {
            return base.Channel.saldo(request);
        }
        
        public CasaGuerrero.WSMTCenter.OutputSaldo saldo(CasaGuerrero.WSMTCenter.InputSaldo inputSaldo) {
            CasaGuerrero.WSMTCenter.saldoRequest inValue = new CasaGuerrero.WSMTCenter.saldoRequest();
            inValue.Body = new CasaGuerrero.WSMTCenter.saldoRequestBody();
            inValue.Body.inputSaldo = inputSaldo;
            CasaGuerrero.WSMTCenter.saldoResponse retVal = ((CasaGuerrero.WSMTCenter.ServiceSoap)(this)).saldo(inValue);
            return retVal.Body.saldoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.saldoResponse> CasaGuerrero.WSMTCenter.ServiceSoap.saldoAsync(CasaGuerrero.WSMTCenter.saldoRequest request) {
            return base.Channel.saldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CasaGuerrero.WSMTCenter.saldoResponse> saldoAsync(CasaGuerrero.WSMTCenter.InputSaldo inputSaldo) {
            CasaGuerrero.WSMTCenter.saldoRequest inValue = new CasaGuerrero.WSMTCenter.saldoRequest();
            inValue.Body = new CasaGuerrero.WSMTCenter.saldoRequestBody();
            inValue.Body.inputSaldo = inputSaldo;
            return ((CasaGuerrero.WSMTCenter.ServiceSoap)(this)).saldoAsync(inValue);
        }
    }
}
